from pathlib import Path
import subprocess, xml.etree.ElementTree as ET
p=Path(__file__).parent
items=[('01-hola', '开口即好', 'HELLO / MONOGRAM', '#D36148', '#FAEDE6', '把小写 h 的肩部延展成对话尾巴。Hola 的首字母成为一个正在开口的符号，轻松、友好，也适合独立作应用图标。', '<path d="M26 20v57h13V51c0-9 5-14 13-14s12 5 12 14v18c0 10 7 15 17 13V70c-4 0-4-2-4-6V50c0-16-9-26-23-26-6 0-11 2-15 6V20Z" fill="currentColor"/>'), ('02-yan', '言之有意', 'YAN / LANGUAGE', '#346B57', '#EAF1E8', '从「言」字提取点、横与口：上方是表达，下方是承载原意的开口。中文辨识最强，呈现克制、可信的编辑气质。', '<g fill="currentColor"><rect x="43" y="13" width="14" height="9" rx="4.5"/><rect x="20" y="28" width="60" height="7" rx="3.5"/><rect x="32" y="42" width="36" height="6" rx="3"/></g><path d="M31 59h38v17H31Z" fill="none" stroke="currentColor" stroke-width="7" stroke-linejoin="round"/>'), ('03-unfold', '让意思舒展', 'UNFOLD / EXPRESSION', '#5265A4', '#ECEFF7', '同一条带子由紧凑的回环舒展成开放的弧线：意思仍是你的，表达变得从容。抽象、有动感，适合建立独立品牌。', '<path d="M21 66V43c0-13 8-21 19-21s19 8 19 21v18c0 11-7 18-16 18s-16-7-16-16 7-16 16-16h21c10 0 15-6 15-15" fill="none" stroke="currentColor" stroke-width="9" stroke-linecap="round" stroke-linejoin="round"/>'), ('04-seed', '本意生花', 'SEED / MEANING', '#A66730', '#F5EEE0', '两枚引号像种子展开的叶片，中间的留白保留生长空间。将文字、原意与更好的表达联系起来，柔和而有人文感。', '<g fill="currentColor"><path d="M47 57C24 59 15 44 20 23c22-2 34 10 27 34Z"/><path d="M53 57c-7-23 5-35 27-34 5 21-4 36-27 34Z"/></g><path d="M50 60v19" fill="none" stroke="currentColor" stroke-width="8" stroke-linecap="round"/>'), ('05-resonance', '话有所应', 'RESONANCE / UNDERSTOOD', '#986078', '#F4EAF0', '两道相向的括弧，围住一颗不变的原点。原点代表你的意思，括弧代表更妥帖的表达与接收；简洁、安静、易缩放。', '<g fill="none" stroke="currentColor" stroke-width="10" stroke-linecap="round"><path d="M34 23C12 36 12 64 34 77"/><path d="M66 23c22 13 22 41 0 54"/></g><circle cx="50" cy="50" r="10" fill="currentColor"/>')]
def svg(body,color=None):
    return f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"'+(f' color="{color}"' if color else '')+'>'+body+'</svg>'
cards=[]
board=['<svg xmlns="http://www.w3.org/2000/svg" width="1600" height="850" viewBox="0 0 1600 850"><rect width="1600" height="850" fill="#F8F7F4"/><g font-family="Helvetica, Arial, sans-serif" fill="#242B29"><text x="64" y="87" font-size="46" font-weight="600">Hola · 言好</text><text x="66" y="126" font-size="17" fill="#6B726E">你的意思，更好的表达。 /  五个品牌方向</text><text x="1530" y="86" text-anchor="end" font-size="13" letter-spacing="2">LOGO EXPLORATION — 2026</text>']
for i,(slug,name,sub,col,bg,desc,body) in enumerate(items):
    (p/(slug+'.svg')).write_text(svg(body))
    (p/(slug+'-color.svg')).write_text(svg(body,col))
    subprocess.run(['rsvg-convert','-w','1024','-h','1024','-o',str(p/(slug+'.png')),str(p/(slug+'-color.svg'))],check=True)
    icon=svg(body)
    cards.append(f'<article style="--accent:{col};--tint:{bg}"><div class="art"><div class="brand">{icon}<strong>Hola <span>· 言好</span></strong><em>你的意思，更好的表达。</em></div></div><div class="info"><small>0{i+1} / {sub}</small><h2>{name}</h2><p>{desc}</p><div class="samples"><span style="width:16px">{icon}</span><span style="width:24px">{icon}</span><span style="width:40px">{icon}</span><span class="inverse">{icon}</span></div><div class="links"><a href="{slug}.svg" download>SVG</a><a href="{slug}.png" download>PNG</a><button onclick="choose(this,{i+1})">选择这个方向</button></div></div></article>')
    x=64+i*300
    board.append(f'<rect x="{x}" y="197" width="276" height="300" rx="22" fill="{bg}"/><svg x="{x+48}" y="246" width="180" height="180" viewBox="0 0 100 100" color="{col}">{body}</svg><text x="{x}" y="541" font-size="13" fill="#6B726E">0{i+1} / {sub.split(" / ")[0]}</text><text x="{x}" y="580" font-size="25" font-weight="600">{name}</text><svg x="{x}" y="620" width="24" height="24" viewBox="0 0 100 100" color="#242B29">{body.replace("nib","nibsmall")}</svg><svg x="{x+48}" y="612" width="40" height="40" viewBox="0 0 100 100" color="#242B29">{body.replace("nib","nibmedium")}</svg><rect x="{x+119}" y="601" width="60" height="60" rx="14" fill="#242B29"/><svg x="{x+129}" y="611" width="40" height="40" viewBox="0 0 100 100" color="white">{body.replace("nib","nibwhite")}</svg>')
board.append('<path d="M64 724H1536" stroke="#DDDFDA"/><text x="64" y="776" font-size="16" fill="#6B726E">macOS 文字润色助手 · 彩色主标 / 单色缩略 / 深色适配</text><text x="1536" y="776" text-anchor="end" font-size="15" fill="#6B726E">推荐 01：亲和品牌    /    02：中文辨识</text></g></svg>')
(p/'overview.svg').write_text(''.join(board))
subprocess.run(['rsvg-convert','-o',str(p/'overview.png'),str(p/'overview.svg')],check=True)
html='''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Hola · 言好 · Logo 方案</title><style>
*{box-sizing:border-box}body{margin:0;background:#f8f7f4;color:#242b29;font-family:-apple-system,BlinkMacSystemFont,sans-serif}main{max-width:1440px;margin:auto;padding:64px 32px}header{display:flex;justify-content:space-between;gap:28px;align-items:end;margin-bottom:48px}h1{font-size:54px;letter-spacing:-2px;margin:0 0 14px}header p{color:#68716d;font-size:18px;margin:0}button,a{font:inherit}button{cursor:pointer;border:1px solid #c8cdc7;border-radius:20px;padding:9px 15px;background:transparent;color:inherit}button:focus-visible,a:focus-visible{outline:3px solid #268775;outline-offset:4px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:28px}article{border:1px solid #e0e2dc;border-radius:24px;overflow:hidden;background:#fff;transition:transform .2s}article:hover{transform:translateY(-3px)}article.selected{outline:3px solid var(--accent)}.art{height:250px;background:var(--tint);color:var(--accent);display:grid;place-items:center}.art svg{width:120px;height:120px}.brand{text-align:center}.brand>svg{display:block;margin:0 auto 6px}.brand strong{display:block;font-size:26px;letter-spacing:-1px}.brand strong span{font-size:20px;letter-spacing:0}.brand em{display:block;margin-top:12px;font-size:12px;font-style:normal;letter-spacing:1px}.info{padding:26px}small{font-size:10px;letter-spacing:1.5px;color:#777}h2{font-size:24px;margin:12px 0}p{line-height:1.8;font-size:14px;color:#68716d;min-height:76px}.samples{display:flex;align-items:center;gap:22px;height:66px;color:#242b29}.samples span{display:inline-flex}.inverse{width:48px;padding:4px;background:#242b29;color:white;border-radius:12px}.links{border-top:1px solid #e8e9e4;margin-top:20px;padding-top:18px;display:flex;align-items:center;gap:16px}a{font-size:12px;color:inherit;text-decoration:none}.links button{margin-left:auto;font-size:12px}footer{margin-top:40px;color:#68716d;font-size:13px}.mono .art{color:#242b29;background:#eeefeb}.dark .art{color:#fff;background:#242b29}@media(max-width:1050px){.grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:640px){main{padding:32px 20px}.grid{grid-template-columns:1fr}header{display:block}header button{margin-top:20px}h1{font-size:42px}}@media(prefers-reduced-motion:reduce){article{transition:none}}
</style><main><header><div><h1>Hola · 言好</h1><p>你的意思，更好的表达。</p></div><button id="mode" onclick="cycle()">外观：品牌色</button></header><div class="grid">'''+''.join(cards)+'''</div><footer><p id="selection" aria-live="polite">点击选中喜欢的方向，再在聊天里告诉我编号。推荐 01「开口即好」或 02「言之有意」。</p>SVG 为透明底单色矢量；PNG 为 1024 × 1024 透明底品牌色。页面可离线使用。</footer></main><script>let mode=0;function cycle(){mode=(mode+1)%3;document.body.className=['','mono','dark'][mode];document.getElementById('mode').textContent='外观：'+['品牌色','单色','深色'][mode]}function choose(b,n){document.querySelectorAll('article').forEach(a=>a.classList.remove('selected'));b.closest('article').classList.add('selected');document.getElementById('selection').textContent='已选方向 0'+n+'。请在聊天里告诉我编号和希望调整的细节。'}</script></html>'''
(p/'index.html').write_text(html)
(p/'README.md').write_text('# Hola · 言好 Logo 探索\n\n根据 Sources/main.swift 的当前实现，产品是 macOS 菜单栏文字润色助手，重点是保持原意、改善语气与流畅度。仓库主 README 仍描述早期 AX 测试工具，设计以源码为依据。\n\n使用 logo-generator Skill 的几何 / 线条 / 字母抽象设计流程，按用户要求交付五款。展示页沿用 Skill 的卡片比较方式，改为无外部依赖的离线页面。\n\n'+ '\n\n'.join(f'## {i+1}. {n}\n\n{d}\n\n主色：{c}。文件：`{s}.svg`、`{s}-color.svg`、`{s}.png`。' for i,(s,n,_,c,_,d,_) in enumerate(items))+'\n\n打开 index.html 比较品牌色、单色和深色，以及 16 / 24 / 40 px 缩略。小尺寸为浏览器预览，尚未集成 macOS 状态栏实测。图案为可编辑 SVG，PNG 由 rsvg-convert 渲染。此阶段未调用生成式图像服务；选定方向后再制作应用图标或展示图。\n')
for f in p.glob('*.svg'): ET.parse(f)
print('Generated 5 concepts, 5 PNGs, SVG originals, overview and interactive HTML; all SVG XML valid.')
